### ISSUE TITLE
Type not found : sys.db.Sqlite when using hx4compat

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/hx4compat#3]
In a C++/Hl/Neko/Php project, when using hx4compat there is still an error when trying to import `sys.db.Sqlite`.

```
Type not found : sys.db.Sqlite
```

Interestingly, the error is slightly different if hx4compat is omitted altogether, where it includes line references:
```
src/Main.hx:1: characters 8-21 : Type not found : sys.db.Sqlite
```
[example.zip](https://github.com/HaxeFoundation/hx4compat/files/13751875/example.zip)

**Comment by kLabz** [comment]
Try removing `@:coreApi` there

**Comment by tobil4sk** [comment]
> Try removing @:coreApi there

Yep, thanks, that does the job: #4.
